<x-app-layout>
    <x-slot name="header"><div class="flex justify-between items-center"><h2 class="font-semibold text-xl text-gray-800 leading-tight">{{ __('My Incident Reports') }}</h2><a href="{{ route('teacher.incidents.create') }}" class="inline-flex items-center px-4 py-2 bg-red-600 rounded-md text-xs font-semibold text-white uppercase">+ Report New Incident</a></div></x-slot>
    <div class="bg-white shadow-sm rounded-lg overflow-hidden">
        <table class="min-w-full divide-y divide-gray-200">
            <thead class="bg-gray-50"><tr><th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Date</th><th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Student</th><th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Severity</th><th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Offense</th><th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Status</th></tr></thead>
            <tbody class="divide-y divide-gray-200 bg-white">@forelse($incidentReports as $incident)<tr><td class="px-6 py-4 text-sm text-gray-500">{{ $incident->incident_date?->format('M d, Y') }}</td><td class="px-6 py-4 text-sm text-gray-900">{{ $incident->student->lrn }} @if($incident->student->full_name) — {{ $incident->student->full_name }} @endif</td><td class="px-6 py-4 text-sm capitalize">{{ $incident->severity }}</td><td class="px-6 py-4 text-sm text-gray-900">{{ str_replace('_', ' ', $incident->offense_type) }}</td><td class="px-6 py-4 text-sm capitalize">{{ str_replace('_', ' ', $incident->status) }}</td></tr>@empty<tr><td colspan="5" class="px-6 py-6 text-sm text-gray-500">No incident reports submitted yet.</td></tr>@endforelse</tbody>
        </table>
    </div>
</x-app-layout>
